name: flutter_movie_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  provider: ^6.0.2
  get: ^4.6.1
  flutterfire_ui: ^0.3.1
  firebase_database_web: ^0.2.0+5
  cloud_firestore: ^3.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

