// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLb2uIp5mejPFi_mHpQtSuYUa7o-XwIvQ',
    appId: '1:202466527093:web:84d79e7565e422f593753c',
    messagingSenderId: '202466527093',
    projectId: 'flutter-movie-app-aa745',
    authDomain: 'flutter-movie-app-aa745.firebaseapp.com',
    storageBucket: 'flutter-movie-app-aa745.appspot.com',
    measurementId: 'G-3KR448W8G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnc6dVYNLMFWLdmyksIzYo_XwII79Ix-o',
    appId: '1:202466527093:android:09ab8b3d551eb00293753c',
    messagingSenderId: '202466527093',
    projectId: 'flutter-movie-app-aa745',
    storageBucket: 'flutter-movie-app-aa745.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPqIpFvmneIgz_CDywcO_3uXP_gJVJUK8',
    appId: '1:202466527093:ios:9cd439073840751093753c',
    messagingSenderId: '202466527093',
    projectId: 'flutter-movie-app-aa745',
    storageBucket: 'flutter-movie-app-aa745.appspot.com',
    iosClientId: '202466527093-696snmnhvqkie476uk8c5r1tsmv7jgr9.apps.googleusercontent.com',
    iosBundleId: 'com.ex',
  );
}
